// ============================================================================
// Minimal repro: Oracle.EntityFrameworkCore orphans "SELECT :B1 FROM DUAL"
// ref cursors when a statement AFTER THE FIRST in a SaveChanges batch fails,
// and the leaked cursors are NOT released when the connection is returned to
// the pool - so a long-running service slowly saturates the reused session.
//
// Mechanism: with key/value generation active (ValueGeneratedOnAdd), the
// provider batches DML into an anonymous PL/SQL block where each INSERT is
// followed by an OPEN <refcursor> FOR SELECT <returned values> FROM DUAL.
// If a later INSERT raises (e.g. ORA-12899), the block aborts AFTER the ref
// cursors of the preceding statements were opened: the client never receives
// their handles, so they stay open on the session. Disposing the DbContext
// (returning the connection to the pool), rollback and
// OracleConnection.PurgeStatementCache do NOT release them; only killing the
// physical session (ClearPool) does. With pooling the same session is reused,
// so every failed batch adds cursors until it hits ORA-01000.
//
// This repro uses DEFAULT pooling (no connection-string changes): every
// iteration creates a FRESH DbContext, fails SaveChanges, and disposes it - the
// connection goes back to the pool and the next iteration gets the SAME
// physical session (printed SID stays constant). The open-cursor count on that
// session still climbs, which proves that returning the connection to the pool
// does not release the leak. This is the production mechanism.
//
// Modes (2nd argument):
//   1 (default) = HEAD + good DETAIL + failing DETAIL in the SAME SaveChanges
//                 -> LEAK: cursors grow on the reused pooled session every time
//   2 = same as 1 but MaxBatchSize(1)
//                 -> NO leak: flat (the failing statement has no predecessors)
//
// NOTE on provider versions: on 8.23.x a HEAD insert before the failing DETAIL
// is enough to leak. On 10.23.x the provider composes batches differently
// (commands appear to be grouped per table), so the leak requires a SUCCESSFUL
// row of the SAME table before the failing one in the block - hence the good
// DETAIL row below, which makes the repro leak on BOTH provider lines.
// The mechanism is unchanged: orphaned cursors = ref cursors already OPENed
// in the same PL/SQL block before the failing statement.
//
// Usage:
//   dotnet run -- "<oracle connection string>" [mode] [iterations]
//   (or set the ORACLE_CONN environment variable)
//
// Monitoring requires SELECT on V$OPEN_CURSOR; without the grant the repro
// still works: in mode 1 the session eventually dies with ORA-01000.
//
// Cleanup:
//   DROP TABLE CURSOR_LEAK_HEAD PURGE;
//   DROP TABLE CURSOR_LEAK_DETAIL PURGE;
// ============================================================================

using Microsoft.EntityFrameworkCore;
using Oracle.ManagedDataAccess.Client;

string connString = args.Length > 0
    ? args[0]
    : Environment.GetEnvironmentVariable("ORACLE_CONN")
      ?? throw new InvalidOperationException(
          "Pass the connection string as 1st argument or set ORACLE_CONN.");
int mode = args.Length > 1 ? int.Parse(args[1]) : 1;
int iterations = args.Length > 2 ? int.Parse(args[2]) : 200;

TestContext.ConnString = connString;
TestContext.MaxBatch = mode == 2 ? 1 : 10;

// --- setup: create the two test tables (ignore ORA-00955 = already exists)
await using (var setup = new TestContext())
{
    await setup.Database.ExecuteSqlRawAsync("""
        BEGIN
          EXECUTE IMMEDIATE 'CREATE TABLE CURSOR_LEAK_HEAD (
             ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
             PAYLOAD VARCHAR2(50))';
          EXECUTE IMMEDIATE 'CREATE TABLE CURSOR_LEAK_DETAIL (
             ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
             SHORT_COL VARCHAR2(10))';
        EXCEPTION WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
        END;
        """);
}

Console.WriteLine($"mode={mode}  MaxBatchSize={TestContext.MaxBatch}  iterations={iterations}");
Console.WriteLine($"start: {await MonitorAsync()}");
Console.WriteLine("(default pooling, no connection-string changes: each iteration uses a fresh");
Console.WriteLine(" DbContext that is disposed back to the pool, which hands the SAME session back)");
Console.WriteLine();

int failed = 0;
var oraErrors = new Dictionary<int, int>();                     // distinct ORA code -> occurrences
for (int i = 1; i <= iterations; i++)
{
    // FRESH context every iteration: it is disposed at the end of the block,
    // returning the connection to the pool
    await using (var ctx = new TestContext())
    {
        ctx.Heads.Add(new Head { Payload = "OK" });             // statement #1: succeeds -> its ref cursor gets opened
        ctx.Details.Add(new Detail { ShortCol = new string('X', 1) });
        ctx.Details.Add(new Detail { ShortCol = new string('X', 50) });// ORA-12899: 50 chars > VARCHAR2(10)

        try
        {
            await ctx.SaveChangesAsync();
        }
        catch (DbUpdateException ex)
        {
            failed++;                                           // expected: every SaveChanges fails

            // NOTE: DbUpdateException.Message is the generic EF text; the ORA
            // code lives in the inner OracleException -> walk the chain.
            OracleException? ora = ex.InnerException as OracleException;

            int code = ora?.Number ?? 0;
            oraErrors[code] = oraErrors.TryGetValue(code, out var c) ? c + 1 : 1;
            if (oraErrors[code] == 1)                           // log every DISTINCT ORA error once
                Console.WriteLine($"iter {i,4}: first ORA-{code:D5}: {ora?.Message.Split('\n')[0]}");

            if (code == 1000)
            {
                Console.WriteLine($"iter {i,4}: ORA-01000 maximum open cursors exceeded -> the pooled session is saturated even though the connection was returned to the pool after every iteration");
                break;                                          // the pooled session is unusable from here on
            }
        }
    } 

    if (i % 25 == 0)
        Console.WriteLine($"iter {i,4}: failed SaveChanges={failed,4}  {await MonitorAsync()}");
}

Console.WriteLine();
Console.WriteLine("ORA errors seen:");
foreach (var kv in oraErrors.OrderBy(k => k.Key))
    Console.WriteLine($"  ORA-{kv.Key:D5} x {kv.Value}");

Console.WriteLine();
Console.WriteLine("Top open cursors on the pooled session (v$open_cursor):");
await DumpTopCursorsAsync();

Console.WriteLine();
Console.WriteLine("Expected:");
Console.WriteLine("  mode 1 -> count grows ~ +1 per failed SaveChanges on the SAME reused SID,");
Console.WriteLine("            even though the connection is returned to the pool each iteration;");
Console.WriteLine("            top sql_text = 'SELECT :B1 FROM DUAL'");
Console.WriteLine("  mode 2 -> flat (MaxBatchSize=1: the failing statement has no predecessors)");

// ---------------------------------------------------------------------------

// Each probe borrows a short-lived connection from the pool and releases it, so
// it never pins a session: with default pooling and this single-threaded loop
// the pool keeps handing back the same physical session (constant SID).
async Task<string> MonitorAsync()
{
    try
    {
        await using var probe = new TestContext();
        var conn = probe.Database.GetDbConnection();
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            SELECT SYS_CONTEXT('USERENV','SID'),
                   (SELECT COUNT(*) FROM v$open_cursor
                    WHERE sid = SYS_CONTEXT('USERENV','SID'))
            FROM DUAL
            """;
        await using var r = await cmd.ExecuteReaderAsync();
        await r.ReadAsync();
        return $"SID={r.GetValue(0)}  open cursors on session={r.GetValue(1)}";
    }
    catch (OracleException)
    {
        return "open cursors = n/a (no grant on V$OPEN_CURSOR)";
    }
}

async Task DumpTopCursorsAsync()
{
    try
    {
        await using var probe = new TestContext();
        var conn = probe.Database.GetDbConnection();
        await conn.OpenAsync();
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            SELECT cursor_type, sql_text, COUNT(*)
            FROM   v$open_cursor
            WHERE  sid = SYS_CONTEXT('USERENV','SID')
            GROUP  BY cursor_type, sql_text
            ORDER  BY COUNT(*) DESC
            FETCH FIRST 5 ROWS ONLY
            """;
        await using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
            Console.WriteLine($"  {reader.GetInt32(2),6} x  [{reader.GetString(0)}]  {reader.GetString(1)}");
    }
    catch (OracleException ex)
    {
        Console.WriteLine($"  n/a ({ex.Message.Split('\n')[0]})");
    }
}

// ---------------------------------------------------------------------------

public class Head
{
    public int Id { get; set; }
    public string Payload { get; set; } = "";
}

public class Detail
{
    public int Id { get; set; }
    public string ShortCol { get; set; } = "";
}

public class TestContext : DbContext
{
    public static string ConnString = "";
    public static int MaxBatch = 10;

    public DbSet<Head> Heads => Set<Head>();
    public DbSet<Detail> Details => Set<Detail>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseOracle(ConnString, o => o.MaxBatchSize(MaxBatch));
        // Uncomment to see the generated PL/SQL block (DECLARE ... OPEN ... FOR SELECT ... FROM DUAL):
        //optionsBuilder.LogTo(Console.WriteLine, new[] { Microsoft.EntityFrameworkCore.Diagnostics.RelationalEventId.CommandExecuting });
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Head>(e =>
        {
            e.ToTable("CURSOR_LEAK_HEAD");
            e.Property(x => x.Id).HasColumnName("ID").ValueGeneratedOnAdd();
            e.Property(x => x.Payload).HasColumnName("PAYLOAD");
        });

        modelBuilder.Entity<Detail>(e =>
        {
            e.ToTable("CURSOR_LEAK_DETAIL");
            e.Property(x => x.Id).HasColumnName("ID").ValueGeneratedOnAdd();
            e.Property(x => x.ShortCol).HasColumnName("SHORT_COL");
        });
    }
}
